#!/usr/bin/env php
<?php
/**
 * 修复eeprom的mac地址,生成路由宝序列号
 * User: sinabs
 * Date: 16/8/17
 * Time: 下午3:57
 */
$bin = $_SERVER['argv'][1];
if (!file_exists($bin)) {
    exit(sprintf('路径为:%s的bin文件不存在', $bin));
}

if (!is_writable($bin)) {
    exit(sprintf('路径为:%s的bin文件不可写', $bin));
}

if (!$handle = fopen($bin, 'r+')) {
    exit(sprintf('不能打开文件%s', $bin));
}

//修改mac地址
editMac16($handle, 4);
editMac16($handle, 40);
editMac16($handle, 46);
setNewNsCode($handle, 272);

fclose($handle);
/**
 * 写入sn的序列号
 * @param $handle
 * @param $offset
 */
function setNewNsCode($handle, $offset)
{
    if (fseek($handle, 46) != -1) {
        $buffer = fread($handle, 6);
        $mac    = strtoupper(bin2hex($buffer));
        $sn     = preg_replace('/[a-f]/i', '', md5($mac));
        $sn     = '2115'.substr($sn, 0, 12);
        echo sprintf("mac:%s sn:%s\n", $mac, $sn);

        //写入sn序列号
        if (fseek($handle, $offset) != -1) {
            $sn_arr = str_split($sn, 2);
            foreach ($sn_arr as $hex) {
                fwrite($handle, pack('C1', gmp_init('0x'.$hex)));
            }
        }
    }
}

/**
 * @param $handle
 * @param $offset
 */
function editMac16($handle, $offset)
{
    if (fseek($handle, $offset) != -1) {
        //改ICON:youku.png
        fwrite($handle, pack('C3', 0x54, 0x36, 0x9b));

        $buffer = fread($handle, 1);
        $a      = changeHex($buffer, 3);
        echo sprintf("offset:%s %s => %s\n", $offset + 3, bin2hex($buffer), $a);

        $buffer = fread($handle, 1);
        $b      = changeHex($buffer, 2);
        echo sprintf("offset:%s %s => %s\n", $offset + 4, bin2hex($buffer), $b);

        $buffer = fread($handle, 1);
        $c      = changeHex($buffer, 1);
        echo sprintf("offset:%s %s => %s\n", $offset + 5, bin2hex($buffer), $c);

        //write new mac
        if (fseek($handle, $offset + 3) != -1) {
            fwrite($handle, hex2bin($a).hex2bin($b).hex2bin($c));
        }
    }
}


/**
 * @param $buffer
 * @param $num
 * @return string
 */
function changeHex($buffer, $num = 1)
{
    $dec = hexdec(bin2hex($buffer));
    if ($dec < 250) {
        $dec = $dec + $num;
    } else {
        $dec = $dec - $num;
    }
    return dechex($dec);
}
